### ISSUE TITLE
Appropriate values for model_parallelism and tokens_per_batch to train a t5.small_ssm model on v3_512, v3_1024 and v3_2048 TPUs

### ISSUE THREAD

**Issue by sbhaktha** [tensorflow/mesh#232]
Hello,

I cannot figure out appropriate values for the `model_parallelism` and `tokens_per_batch` parameters to train a t5 small_ssm model. Specifically, what I am trying to do is distill from an `xxl_ssm` teacher model that was fine-tuned on Natural Questions, to a `small_ssm` student model. I need to fit both the teacher and student models in memory and I attempted to do this training on a v3-256 but got OOM issues. I tried several different combinations of the parameters on v3-512 and v3-1024 TPUs but couldn't get any to work. My command line currently looks like this-

```
python -m t5.models.mesh_transformer_main \
    --tpu=<v3_1024_tpu> \
    --gcp_project=<...> \
    --tpu_zone=<...> \
    --model_dir=<...> \
    --gin_file="dataset.gin" \
    --gin_file="distillation_nqopen_xxl_ssm_to_small_ssm_operative_config.gin" \
    --gin_param="MIXTURE_NAME = <...>" \
    --gin_param="utils.run.save_checkpoints_steps=<...>" \
    --gin_param="utils.run.batch_size=('tokens_per_batch', 393216)" \
    --gin_param="utils.run.train_steps=<...> \
    --gin_param="constant_learning_rate.learning_rate=<...>" \
    --gin_param="utils.tpu_mesh_shape.tpu_topology='16x32'" \
    --gin_param="utils.tpu_mesh_shape.model_parallelism=8"   \
```

The distillation gin file is attached.
[distillation_nqopen_xxl_ssm_to_small_ssm_operative_config.gin.txt](https://github.com/tensorflow/mesh/files/5514942/distillation_nqopen_xxl_ssm_to_small_ssm_operative_config.gin.txt)

Running the above script on a `v3-1024` with the attached `gin` file, I get the error:

```
WARNING:tensorflow:Reraising captured error
W1110 05:11:05.038959 140634039817600 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 264, in <module>
    console_entry_point()
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 261, in console_en
try_point
    app.run(main)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main  
    sys.exit(main(argv))
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 255, in main
    model_dir=FLAGS.model_dir)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_rer
aise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2302, in run
    skip_seen_data=skip_seen_data)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1615, in train_m
odel
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py",
 line 3089, in train
    rendezvous.raise_errors()
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py"
, line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py",
 line 3084, in train
    saving_listeners=saving_listeners)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 34
9, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 11
75, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 12
04, in _train_model_default
    self.config)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py",
 line 2921, in _call_model_fn
    config)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3212, in _model_fn
    _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn))
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3654, in _train_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/tpu/tpu.py", line 1665, in split_compile_and_shard
    name=name)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/tpu/tpu.py", line 1380, in split_compile_and_replicate
    outputs = computation(*computation_inputs)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3640, in multi_tpu_train_steps_on_single_shard
    inputs=[0, _INITIAL_LOSS])
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/tpu/training_loop.py", line 178, in while_loop
    condition_wrapper, body_wrapper, inputs, name="", parallel_iterations=1)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2774, in while_loop
    return_same_structure)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2256, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2181, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow/python/tpu/training_loop.py", line 121, in body_wrapper
    outputs = body(*(inputs + dequeue_ops))
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3639, in <lambda>
    lambda i, loss: [i + 1, single_tpu_train_step(i)],
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1753, in train_step
    self._call_model_fn(features, labels))
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 686, in my_model_fn
    log_file=model_info_file)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 718, in __init__
    self.autostack()
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 836, in autostack
    max_combined_slice_size=max_combined_slice_size)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 513, in rewrite_stack_variables
    slice_size = mesh_impl.slice_size(op.shape)
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 1004, in slice_size
    return list_product(self.slice_shape(tensor_shape))
  File "/home/sumithrab/miniconda/envs/t2t/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 977, in slice_shape
    % (tensor_shape, tensor_layout))
ValueError: Tensor dimension size not divisible by mesh dimension size: tensor_shape=Shape[heads=6, buckets=32] tensor_layout=TensorLayout(1, None)
  In call to configurable 'run' (<function run at 0x7fe77bf299e0>)
```

What are good values for these parameters and how do we get at them?
Your help is greatly appreciated.

@danyaljj FYI

**Comment by sbhaktha** [comment]
Moving issue to `google-research/text-to-text-transfer-transformer` repo.
